# Generated by Django 4.1.5 on 2023-03-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_myprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(default='', upload_to='profile/images'),
            preserve_default=False,
        ),
    ]
