# Generated by Django 4.1.5 on 2023-03-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bimage',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
