# Generated by Django 4.1.5 on 2023-03-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_clgname_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('toauthor', models.CharField(max_length=20)),
                ('fcategory', models.CharField(max_length=20)),
                ('ftitle', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=20)),
                ('fcontent', models.TextField()),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
