# Generated by Django 4.1.5 on 2023-03-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_feedback_toauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(default='', upload_to='pimages/'),
        ),
    ]
