# Generated by Django 4.1.5 on 2023-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profile_aboutme_profile_flink_profile_ilink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='pimages/'),
        ),
    ]
