# Generated by Django 4.1.5 on 2023-03-31 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0029_alter_feedback_toauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='toauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
